name: Scaffold Java Library

on:
  workflow_call:
    inputs:
      groupId:
        description: Java groupId (e.g., com.mycompany)
        required: true
        type: string
      artifactId:
        description: Artifact ID (e.g., utils-lib)
        required: true
        type: string
        
      javaVersion:
        description: Java Version (e.g., 17)
        required: true
        default: '17'
        type: string
      enableSonar:
        description: Enable SonarQube?
        required: true
        default: "true"
        type: string
      enableCheckmarx:
        description: Enable Checkmarx?
        required: true
        default: "false"
        type: string
      enableOWASP:
        description: Enable OWASP scan?
        required: true
        default: "true"
        type: string

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Cookiecutter
        run: pip install cookiecutter

      - name: Run Cookiecutter Scaffold
        run: |
          cookiecutter https://premalatha755@github.com/premalatha755/cookiecutter-java-lib.git --no-input \
            groupId="${{ github.event.inputs.groupId }}" \
            artifactId="${{ github.event.inputs.artifactId }}" \
            javaVersion="${{ github.event.inputs.javaVersion }}" \
            enable_sonarqube="${{ github.event.inputs.enableSonar }}" \
            enable_checkmarx="${{ github.event.inputs.enableCheckmarx }}" \
            enable_owasp="${{ github.event.inputs.enableOWASP }}"

      - name: Push generated project to new repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cp -R ${{ github.event.inputs.artifactId }}/. .
          gh auth status
          rm temp.txt
          git config user.name "scaffold-bot"
          git config user.email "scaffold-bot@your-org.com"
          git add .
          git commit -m "Initial scaffold"
          git branch -M main
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/premalatha755/${{ github.event.inputs.artifactId }}.git
          git push -u origin main
